spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true


server:
  port: 9090

management:
  endpoint:
    gateway:
      access: unrestricted

info:
  app:
    name: "gateway-server"
    description: "edge server to my ecommerce microservice network"

